library(ggplot2)
View(mtcars)
ggplot(mtcars,aes(x=cyl,y=hp))+geom_bar())
ggplot(mtcars,aes(x=cyl))+geom_bar(binwidth=1)
ggplot(mtcars,aes(x=cyl,stat="count"))+geom_dotplot(binwidth=0.2)
ggplot(ChickWeight,aes(x=weight,stat="count"))+geom_boxplot(binwidth=1)+cord_flip()ggplot(ChickWeight,aes(x=weight,stat="count"))+geom_boxplot(binwidth=1)+coord_flip()
ggplot(mtcars,aes(x=disp,stat="count"))+geom_boxplot(binwidth=1)+coord_flip()+theme((axis.text.y=element_blank(),axis.tricks.y=element_blank()))
ggplot(mtcars,aes(x=disp,stat="count"))+geom_histogram(binwidth = 50)
ggplot(mtcars,aes(x=disp,stat="count"))+geom_density(binwidth = 1)